title: Ava Sound Documentation
description: Official documentation for Ava Sound API

theme: just-the-docs

url: https://tpi-tup-p.github.io
baseurl: "/AvaSoundDocumentation"

aux_links:
  Repository: "https://github.com/TPI-TUP-P/AvaSoundDocumentation"
